### ISSUE TITLE
manyosx

### ISSUE THREAD

**Issue by SylvainCorlay** [jupyter-xeus/xeus-python-wheel#14]
I am looking into how people make OSX wheels, and it seems to be quite heterogeneous. 

I presume that using the oldest possible version of xcode for the broadest binary compatibility is a way to go.

Maybe @scopatz has some insight on this subject!

**Comment by scopatz** [comment]
Hey there @SylvainCorlay! Yeah, I think people just build them locally on their own machines usually.

**Comment by SylvainCorlay** [comment]
Thanks. We are setting up the testing of the wheel on CI - but I have not seem so much out there.

There seems to be a very comprehensive setup by matthew brett for many platforms, but it seems a bit overkill

**Comment by scopatz** [comment]
Yeah I think that is the state of the art
