### ISSUE TITLE
Placing vendored dependency in subprefix

### ISSUE THREAD

**Issue by SylvainCorlay** [jupyter-xeus/xeus-python-wheel#17]
It may be a good thing to place the vendored deps in a subdirectory that is not the general prefix to avoid overriding existing installed files.

**Comment by SylvainCorlay** [comment]
I wonder if this is something that scikit-build can do.

**Comment by JohanMabille** [comment]
According to [this answer](https://github.com/scikit-build/scikit-build/issues/470), it is not feasible for now.

The solution is to make a full static build of xeus-python to avoid potential overwrite of already installed dependencies.
